media:
  - input: public/images
    output: /images
    extensions:
      - jpg
      - jpeg
      - png
      - gif
      - webp
      - svg

components:
  seo:
    fields:
      meta_title:
        type: text
        label: Meta Title
      meta_description:
        type: textarea
        label: Meta Description
      og_image:
        type: text
        label: Open Graph Image URL

content:
  # Main Articles - Curated content from external sources
  articles:
    path: src/content/articles
    view: 
      fields:
        - title
        - publishedDate
        - featured
        - articleType
        - topics
    schema:
      title:
        type: text
        label: Title
        required: true
      subtitle:
        type: text
        label: Subtitle
      originalUrl:
        type: url
        label: Original URL
      source:
        type: text
        label: Source Publication
        required: true
      author:
        type: text
        label: Author
      publishedDate:
        type: datetime
        label: Published Date
        required: true
      foundDate:
        type: datetime
        label: Found Date
      readingTime:
        type: number
        label: Reading Time (minutes)
        required: true
      articleType:
        type: select
        label: Article Type
        required: true
        options:
          - essay
          - podcast
          - video
          - newsletter
          - paper
          - thread
          - book
      topics:
        type: list
        label: Topics
        required: true
        schema:
          type: text
      issueNumber:
        type: number
        label: Issue Number
      featured:
        type: boolean
        label: Featured Article
        default: false
      curatorNotes:
        type: rich-text
        label: Curator Notes
        required: true
        description: "Your thoughts, analysis, and why this article matters"
      excerpt:
        type: textarea
        label: Excerpt
        required: true
        description: "Brief summary of the article"
      pullQuote:
        type: textarea
        label: Pull Quote
        description: "Key quote from the article"
      body:
        type: rich-text
        label: Full Analysis
        required: true

  # Newsletter Issues
  issues:
    path: src/content/issues
    view:
      fields:
        - issueNumber
        - publishDate
        - title
        - theme
    schema:
      issueNumber:
        type: number
        label: Issue Number
        required: true
      publishDate:
        type: datetime
        label: Publish Date
        required: true
      title:
        type: text
        label: Title
        required: true
      theme:
        type: text
        label: Issue Theme
      openingNote:
        type: textarea
        label: Opening Note
        description: "Intro message for the issue"
      closingThought:
        type: textarea
        label: Closing Thought
        description: "Ending reflection for the issue"
      body:
        type: rich-text
        label: Issue Content
        required: true

  # Topics/Categories
  topics:
    path: src/content/topics
    extension: yml
    view:
      fields:
        - name
        - slug
        - featured
        - color
    schema:
      name:
        type: text
        label: Topic Name
        required: true
      slug:
        type: text
        label: URL Slug
        required: true
      description:
        type: textarea
        label: Description
        required: true
      icon:
        type: text
        label: Icon (emoji)
        required: true
      color:
        type: select
        label: Color Theme
        required: true
        options:
          - coral
          - blue
          - mint
          - lavender
          - peach
          - sage
          - yellow
      featured:
        type: boolean
        label: Featured Topic
        default: false

  # Editorial Notes - Curator margin notes and standalone thoughts
  editorial:
    path: src/content/editorial
    extension: yml
    view:
      fields:
        - note
        - type
        - issue_number
        - featured
    schema:
      note:
        type: rich-text
        label: Editorial Note
        required: true
      type:
        type: select
        label: Note Type
        required: true
        options:
          - curator
          - margin
          - standalone
      issue_number:
        type: number
        label: Issue Number
      created_date:
        type: datetime
        label: Created Date
        required: true
      featured:
        type: boolean
        label: Featured Note
        default: false
      position:
        type: select
        label: Position in Issue
        default: middle
        options:
          - top
          - middle
          - bottom

  # Artwork Collection
  artwork:
    path: src/content/artwork
    view:
      fields:
        - title
        - artist
        - year
        - featured_on_homepage
    schema:
      title:
        type: text
        label: Artwork Title
        required: true
      slug:
        type: text
        label: URL Slug
      artist:
        type: text
        label: Artist Name
        required: true
      year:
        type: text
        label: Year Created
      medium:
        type: text
        label: Medium
      dimensions:
        type: text
        label: Dimensions
      image:
        type: text
        label: Image URL
        required: true
      source_institution:
        type: text
        label: Source Institution
      source_url:
        type: url
        label: Source URL
      description:
        type: textarea
        label: Description
      why_featured:
        type: textarea
        label: Why Featured
        description: "Why this artwork was chosen"
      featured_on_homepage:
        type: boolean
        label: Featured on Homepage
        default: false
      created_date:
        type: datetime
        label: Created Date
        required: true
      seo:
        type: component
        component: seo
      body:
        type: rich-text
        label: Extended Description