name = "dumpsterfire"
main = "dist/_worker.js"
compatibility_date = "2024-12-10"
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]

[build]
command = "npm run build"

[[routes]]
pattern = "fromthedumpsterfire.com/*"
zone_name = "fromthedumpsterfire.com"

[[routes]]
pattern = "www.fromthedumpsterfire.com/*"
zone_name = "fromthedumpsterfire.com"

[vars]
SITE_URL = "https://fromthedumpsterfire.com"