name = "dumpsterfire"
main = "workers-site/index.js"
compatibility_date = "2024-12-10"

[site]
bucket = "./dist"

[[routes]]
pattern = "fromthedumpsterfire.com/*"
zone_name = "fromthedumpsterfire.com"

[[routes]]
pattern = "www.fromthedumpsterfire.com/*"
zone_name = "fromthedumpsterfire.com"

[vars]
SITE_URL = "https://fromthedumpsterfire.com"